package(default_visibility = [
    "//gl:__subpackages__",
    "//opengl_tutorials:__subpackages__",
])

cc_library(
    name = "eigen_traits",
    hdrs = ["eigen_traits.h"],
    deps = [
        "//gl/core:core",
        "//utils:eigen_utils",
    ]
)

