cc_library(
    name = "shader",
    hdrs = ["shader.h"],
    deps = [
        "//third_party/glad:glad",
        "//opengl_tutorials/utils:file_utils",
        "@com_google_absl//absl/strings:strings",
        "@com_google_absl//absl/strings:str_format",
    ],
    visibility = ["//opengl_tutorials:__subpackages__"],
)
