cc_library(
    name = "viewer",
    srcs = ["viewer.cpp"],
    hdrs = ["viewer.h"],
    deps = [
        "//opengl_tutorials/core:shader",
        "@glfw//:glfw",
    ],
    visibility = ["//opengl_tutorials:__subpackages__"],
)
