cc_library(
    name = "scene",
    srcs = [
        "program_pool.cpp",
        "font.cpp",
    ],
    hdrs = [
        "program_pool.h",
        "font.h",
    ],
    visibility = [
        "//gl:__subpackages__",
        "//opengl_tutorials:__subpackages__",
    ],
    deps = [
        "//gl/core:core",
    ],
)
