load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "3d_viewer_example",
    srcs = ["main.cpp"],
    deps = [
        "//gl/core",
        "//gl/scene",
        "//gl/viewer",
    ],
)
