package(default_visibility = [
    "//gl:__subpackages__",
    "//opengl_tutorials:__subpackages__",
])

cc_library(
    name = "viewer",
    srcs = ["viewer.cpp"],
    hdrs = ["viewer.h"],
    deps = [
        "//gl/core:core",
        "@glfw//:glfw",
    ],
)
