cc_library(
    name = "file_utils",
    srcs = ["file_utils.h"],
    visibility = ["//opengl_tutorials:__subpackages__"],
    deps = [
        "@com_google_absl//absl/types:optional",
    ]
)

cc_library(
    name = "eigen_utils",
    srcs = ["eigen_utils.h"],
    visibility = ["//opengl_tutorials:__subpackages__"],
    deps = [
        "@org_tuxfamily_eigen//:eigen"
    ]
)

