cc_library(
    name = "file_utils",
    hdrs = ["file_utils.h"],
    visibility = ["//opengl_tutorials:__subpackages__"],
    deps = [
        "@com_google_absl//absl/types:optional",
    ]
)

cc_library(
    name = "eigen_utils",
    hdrs = ["eigen_utils.h"],
    visibility = ["//opengl_tutorials:__subpackages__"],
    deps = [
        "//opengl_tutorials/core:shader",
        "@org_tuxfamily_eigen//:eigen",
    ]
)

cc_library(
    name = "type_utils",
    hdrs = ["type_utils.h"],
    visibility = ["//opengl_tutorials:__subpackages__"],
)

