name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ClangFormat
      uses: DoozyX/clang-format-lint-action@v0.10
      with:
        source: '.'
        exclude: './third_party'
        extensions: 'h,cpp'
        clangFormatVersion: 10
        style: file
